# Generated by Django 3.1.7 on 2021-02-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_the_text', models.CharField(max_length=400)),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
